
    create table Accesorio (
        costo integer not null,
        nombre varchar(255),
        id bigint not null,
        primary key (id)
    )

    create table Arma (
        ataque integer not null,
        costo integer not null,
        defensa integer not null,
        nombre varchar(255),
        id bigint not null,
        primary key (id)
    )

    create table BolsaDeMonedas (
        monedas integer not null,
        id bigint not null,
        primary key (id)
    )

    create table Item (
        id bigint generated by default as identity (start with 1),
        item_id bigint,
        primary key (id)
    )

    create table Personaje (
        id bigint generated by default as identity (start with 1),
        moneda integer not null,
        nombre varchar(255),
        tipo integer,
        primary key (id)
    )

    create table Regalo (
        fraseMotivacional varchar(255),
        nombre varchar(255),
        id bigint not null,
        primary key (id)
    )

    create table Ubicacion (
        id bigint generated by default as identity (start with 1),
        nivel integer not null,
        x integer not null,
        y integer not null,
        nombre varchar(255),
        primary key (id)
    )

    alter table Accesorio 
        add constraint FK_tdgnmmp4k304yqhn3y37cp2i8 
        foreign key (id) 
        references Item

    alter table Arma 
        add constraint FK_fcdyilcovp8fdmvh20qbxflwr 
        foreign key (id) 
        references Item

    alter table BolsaDeMonedas 
        add constraint FK_rjxc2eupxmhymd6feom67fmsj 
        foreign key (id) 
        references Item

    alter table Item 
        add constraint FK_qy77ndheorny7dd5aw6tncqc8 
        foreign key (item_id) 
        references Personaje

    alter table Regalo 
        add constraint FK_347m6xm8qomwlctni9npcilaf 
        foreign key (id) 
        references Item
